### ISSUE TITLE
A fork

### ISSUE THREAD

**Issue by PhilipVinc** [recp/cmt#2]
Hi Recep,

I recently got interested in wrapping Metal in Julia to do some GPGPU computing, and started from your repository to write the wrappers to C that I would need.

I ended up wrapping most of the Compute pipeline, kernel reflection stuff... I think I wrapped most of Metal, except for 3d-rendering-specific stuff because I'm not really interested in it at the moment.

It's all in [my fork](https://github.com/PhilipVinc/cmt), in case you are interested. 

Thanks again for starting this work!

**Comment by recp** [comment]
Hi @PhilipVinc 

Thank you for letting me know and interested in **cmt** project. I couldn't be fast enough to finish the project :) I hope I'll soon. 

Would you like to merge the fork?

---

Also there is another project I'm working on: **gpu** (https://github.com/recp/gpu), see include directory: https://github.com/recp/gpu/tree/master/gpu/gpu/include/gpu . I'll keep **src** and **include** then remove other files.

It uses **cmt** project for Metal, and I want to make it cross platform GPU + GPGPU library (Metal + DirectX + Vulkan...). My render engine (http://github.com/recp/gk) will use that as backend.

After finished gpu library I hope you will find it interesting. It's api may change overtime until first release.
